### PR TITLE
String db

### PR DESCRIPTION
**Pull request by TomConlin**
- String
   - Merge my changes into Kent's which helps necessary files to be found 
   - Note they are very sensitive to query rate. test frugally
   - Include Yeast
 - leftover ancillary scripts for ingest qc

### CODE REVIEW

**Comment by kshefchek** [comment]
+1

>     * Note they are very sensitive to query rate. test frugally

Locally I had hacked in a sleep in between calls in Source.py, but ideally this would be some optional param.

**Comment by TomConlin** [comment]
@kshefchek  what fate for https://data.monarchinitiative.org/dipper/cache/

**Comment by TomConlin** [comment]
Something is different when running locally v.s. on jenkins causing the parse() function to attempt to process files the fetch() function have not retrieved.
I thought it odd Kent would push a script that did not run but mine is doing no better.

clearing my local 'raw/string/' directory and running works locally
the directory is populated them processed.
on jenkins parse attempts to process the empty directory

**Comment by TomConlin** [comment]
mystery solved

the Jenkins script contained a directive to ` --parse_only`
most likely b/c failures due to StringDBs anti server overload policies

**Pull request merged**
