### PR TITLE
AnimalQTLdb.py  to pass Jenkins tests

### PR DESCRIPTION
**Pull request by TomConlin**
ingest was finding rsid where it thought it had p-value score
made ignore all non numeric p-value scores 
(which does not address how or where the wrong  thing happens)

also at least one gene name is given where the id/symbol should be
fixed the particular case and preventing accepting spaces in future gene id/symbols

### CODE REVIEW

**Comment by TomConlin** [comment]
address  #342

**Comment by kshefchek** [comment]
Did they change the order of the columns?

**Comment by TomConlin** [comment]
no, the code matches what I see (casually looking) at the data

**Comment by TomConlin** [comment]
there may be a bad row somewhere but I did not dig for it

**Pull request merged**
