### PR TITLE
Update ontology term to one that exists 

### PR DESCRIPTION
**Pull request by TomConlin**
`assertion_confidence_level` exists in OLS `confidence_score` does not
then fix tests

### CODE REVIEW

**Comment by kshefchek** [comment]
confidence_score is a datatype property and assertion_confidence_level is an object property, and I also have SEPIO:0000168 configured in scigraph and solr, prefer if we kept this for now

**Comment by TomConlin** [comment]
@mbrush  having updates in OLS/Ontobee is out best path forward.

**Comment by kshefchek** [comment]
It looks like SEPIO_0000168 has been in the ontology dating back to 2017, Matt do you know why it's not in OLS?

**Comment by matentzn** [comment]
Seems like SEPIO is still on the 2017 version, and 168 was introduced later. @mbrush and I will make a new release soon I hope, and then this issue will be fixed.

**Pull request closed without merging**
