### PR TITLE
Update curie_map.yaml

### PR DESCRIPTION
**Pull request by vdancik**
Add CURIEs for Human Metabolite Database (http://www.hmdb.ca)

### CODE REVIEW

**Comment by TomConlin** [comment]
Looks fine but what are these to be used for?  

     'SMPDB': 'http://smpdb.ca/view/'
     'HMDB': 'http://www.hmdb.ca/metabolites/'


Are you creating an ingest?

**Comment by vdancik** [comment]
We use the CURIE list for NCATS translator project (https://ncats.nih.gov/translator) and I am integrating metabolomics (HMDB) and small-molecule pathway (SMPDB) databases. So I am proposing to add those for completeness.

**Comment by kshefchek** [comment]
While I'm not opposed, I'm not certain this file should represent the gold standard.  Would it make more sense to use prefix commons for this task?

**Comment by jmcmurry** [comment]
Agree that for Translator purposes, these would be better to go in the Biolink curie map.

**Pull request merged**
