### PR TITLE
Update curie_map.yaml comments

### PR DESCRIPTION
**Pull request by jmcmurry**
Updating comments fields to better reflect what each ontology refers to and the scope of things it is used for.

### CODE REVIEW

**Comment by kshefchek** [comment]
+1

**Comment by jmcmurry** [comment]
This was a long time ago and the build failed for reasons unrelated to these comments. How can we re-initiate this pull request? @DoctorBud

**Comment by jmcmurry** [comment]
Yay! Thanks @DoctorBud for helping to resolve the conflicts.

**Comment by markengelstad** [comment]
+1

**Pull request merged**
