### PR TITLE
Refactor graph_utils, models API, bnode generation

### PR DESCRIPTION
**Pull request by kshefchek**
This is a global refactor that cleans up our models API,

- define abstract base class for a graph, break out rdflib and streaming graph implementations
- split graph_utils into three classes, models class containing basic rdf/owl axioms (addLabel, addIndividual, addType, etc)
- remove nobnode code, bnode skolemization moved to graph class

### CODE REVIEW

**Comment by cmungall** [comment]
+1

some things for later

 - is convenient to just write `dct:isVersionOf` but should we think of a vocabulary module for stronger typing and better introspection
 - this might also be able to take care of some of the repetition of some of the prefix info

**Comment by cmungall** [comment]
is this a false positive fail in travis?

**Comment by kshefchek** [comment]
it's a true positive, still working through updating each source.

**Comment by kshefchek** [comment]
@cmungall @TomConlin this is pretty much ready to go, let me know if you have any comments.

**Pull request merged**
