### PR TITLE
OMIA

### PR DESCRIPTION
**Pull request by TomConlin**
seemed to be an (intermittent?) problem following redirects

### CODE REVIEW

**Comment by TomConlin** [comment]
between local testing an running via jenkins
input changed.

now has a link to OMIM:10700 which does not exist 
have a email in suggesting they append a zero making it OMIM:107000
which is believable scanning the papers.

**Comment by TomConlin** [comment]
OMIA  has replied they will try and fix it within a day or so

**Comment by kshefchek** [comment]
Can you inquire about their drop in data? I never sent a second email.

**Comment by TomConlin** [comment]
Already did by way of requesting release notes:

     ...am wondering if there could be some sort of OMIA release notes 
    to help me figure out why sometimes the data just seems to disappear.

**Pull request merged**
