### PR TITLE
Change ensembl URL and emit error message when non-200 is received

### PR DESCRIPTION
**Pull request by justaddcoffee**
Two changes: 
- switched to 'www.ensembl.org'  from 'uswest.ensembl.org' - the latter seems to have not worked for the last few days
- emit an error message when querying from `/biomart/martservice` fails (this was silently failing previously)

### CODE REVIEW

**Comment by TomConlin** [comment]
> switched to 'www.ensembl.org' from 'uswest.ensembl.org' - the latter seems to have not worked for the last few days

The only observable difference I notice here is the deletion of the comment that provides the original/alternative url.   see:  
https://github.com/monarch-initiative/dipper/pull/876/files#diff-15c481a6eeaf8dcc8ff228ecac079919L13

adding checks on return http status codes is an unmitigated good.  +1

Unless `www.ensembl.org` is permanently retired. 
there no benefit from removing the comment I could use 
in a trouble shooting situation.

**Comment by justaddcoffee** [comment]
> The only observable difference I notice here is the deletion of the comment that provides the original/alternative url

Sorry, neglected to commit what I was actually using locally. Actually updated URL to `www.ensembl.org` with last commit

**Comment by TomConlin** [comment]
perfect. thanks

**Comment by justaddcoffee** [comment]
Thanks Tom!

**Pull request merged**
